services:
  db:
    image: gitlab.glynzr.me:5005/elnurbda/sample-proj/postgres:alpine
    container_name: postgres-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      custom_network:
        ipv4_address: ${DB_IP}

  front:
    image: gitlab.glynzr.me:5005/elnurbda/sample-proj/front:latest
    container_name: front
    environment:
      REACT_APP_BACK_API: ${REACT_APP_BACK_API}
    ports:
      - "${FRONT_PORT}:3000"
    networks:
      custom_network:
        ipv4_address: ${FRONT_IP}

  back:
    image: gitlab.glynzr.me:5005/elnurbda/sample-proj/back:latest
    container_name: back
    environment:
      PORT: ${BACK_API_PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${BACK_API_PORT}:${BACK_API_PORT}"
    networks:
      custom_network:
        ipv4_address: ${BACK_IP}

volumes:
  db_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}
